service: cartService

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-central-1'}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
