service: cartService

useDotenv: true

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs14.x
    region: ${opt:region, 'eu-central-1'}
    environment:
        DB_HOST: ${env:DB_HOST}
        DB_USER: ${env:DB_USER}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_NAME: ${env:DB_NAME}
        DB_PORT: ${env:DB_PORT}
        PRODUCTS_API_URL: ${env:PRODUCTS_API_URL}

functions:
    main:
        handler: dist/main.handler
        timeout: 10
        events:
            - http:
                  method: ANY
                  path: /
            - http:
                  method: ANY
                  path: '{proxy+}'
